version: '3.8'

services:
  # 1. Django REST Framework Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartassist_backend_container
    # Volume mapping jo data ko aapke local computer ki D: Drive (D:\smartassist-chatbot\backend) me save rakhegi
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  # 2. React (Vite) Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartassist_frontend_container
    volumes:
      - ./frontend:/app
      - /app/node_modules # Local node_modules ko override hone se bachane ke liye virtual volume
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    restart: always